version: "3.7"

services:
  challange07_fin_api:
    image: postgres
    container_name: challange07_fin_api
    restart: always
    ports:
      - 5432:5432
    enviroment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/postgres
    networks:
      - backend

volumes:
  pgdata:
    driver: local

networks:
  backend:
    driver: "bridge"
